name: Terraform Test Workflow

# Trigger the workflow on every git push
on: [push]

jobs:
  terraform-test:
    # Specifies the runner environment (typically 'docker')
    runs-on: docker
    
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v4

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true