name: Terraform Test Workflow

# Trigger the workflow on every git push
on: [push]

defaults:
  run:
    working-directory: ./terraform

jobs:
  terraform-test:
    # Specifies the runner environment (typically 'docker')
    runs-on: docker
    
    steps:
    - uses: actions/checkout@v4
    - uses: https://github.com/hashicorp/setup-terraform@v4

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      env:
        TF_VAR_proxmox_endpoint: ${{ secrets.PVE_ENDPOINT }}
        TF_VAR_proxmox_username: ${{ secrets.PVE_USERNAME }}
        TF_VAR_proxmox_password: ${{ secrets.PVE_PASSWORD }}

